import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Vicky",
      email: "admin@test.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@test.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },

    {
      name:
        "Blue Star 0.75 Ton 3 Star Rating Window AC (Copper, 2018 Model, 3WAE081YDF, White)",
      category: "Air Conditioners",
      image: "/images/p7.jpg",
      price: 2999,
      countInStock: 12,
      brand: "Blue Star",
      rating: 4.5,
      numReviews: 15,
      description: "Windows AC: Economical & easy to install.",
    },
    {
      name: "LG 1.5 Ton 3 Star Split AC (183EZA, White)",
      category: "Air Conditioners",
      image: "/images/p8.jpg",
      price: 2998,
      countInStock: 7,
      brand: "LG",
      rating: 4.9,
      numReviews: 13,
      description:
        "Split AC with low noise. Affordable compared to inverter split ACs",
    },
    {
      name:
        "Aurion Skipping-Rope Jump Skipping Rope for Men, Women, Weight Loss, Kids, Girls, Children, Adult - Best in Fitness, Sports, Exercise, Workout",
      category: "Skipping Ropes",
      image: "/images/p9.jpg",
      price: 34,
      countInStock: 112,
      brand: "Aurion",
      rating: 3.5,
      numReviews: 95,
      description:
        "Light weighted handles: light weighted handles cause less arm fatigue, which helps you in doing more jumps; It also helps you in not missing the jumps",
    },
    {
      name: "Enamor Unisex-Adult Cotton Face Mask",
      category: "Face Mask",
      image: "/images/p10.jpg",
      price: 13,
      countInStock: 20,
      brand: "Enamor",
      rating: 4.0,
      numReviews: 9,
      description:
        "Care Instructions: Hand Was. Cotton jersey on skin for naturally breathable and moisture-control comfort",
    },
    {
      name: "Genie CARE PRO Women's 6-Layer Reusable Face mask (Pack of 3)",
      category: "FAce Mask",
      image: "/images/p11.jpg",
      price: 23,
      countInStock: 122,
      brand: "Genie",
      rating: 2.8,
      numReviews: 27,
      description:
        "Care Instructions: Hand Wash Color name: Assorted Material: Cotton :: Pattern: Floral Buy Genie Facemasks from our Authorised Sellers - Cloudtail India,Backpack World, Vee Ess Sales Pvt Ltd.",
    },
    {
      name: "Samsung Galaxy M31 (Ocean Blue, 6GB RAM, 128GB Storage)",
      category: "Mobile",
      image: "/images/p12.jpg",
      price: 1999,
      countInStock: 24,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 73,
      description:
        "Quad Camera Setup - 64MP (F1.8) Main Camera +8MP (F2.2) Ultra Wide Camera +5MP(F2.2) Depth Camera +5MP(F2.4) Macro Camera and 32MP (F2.0) front facing Camera",
    },
    {
      name:
        "Canon EOS 1500D 24.1 Digital SLR Camera (Black) with EF S18-55 is II Lens",
      category: "Camera",
      image: "/images/p13.jpg",
      price: 299,
      countInStock: 82,
      brand: "Canon",
      rating: 3.5,
      numReviews: 75,
      description:
        "Sensor: APS-C CMOS Sensor with 24.1 MP (high resolution for large prints and image cropping) ISO: 100-6400 sensitivity range (critical for obtaining grain-free pictures, especially in low light) Image Processor: DIGIC 4+ with 9 autofocus points (important for speed and accuracy of autofocus and burst photography)",
    },
  ],
};
export default data;
